import { Body, Controller, Post, Res } from '@nestjs/common';
import { Response } from 'express';
import { TransformService, ExportSource, ExportVerification } from './transform.service';

type ExportBody = {
  title?: string;
  slides?: { title: string; bullets?: string[]; speakerNotes?: string }[];
  sections?: { heading: string; text: string }[];
  sources?: ExportSource[];
  verification?: ExportVerification;
};

@Controller('api/export')
export class ExportController {
  constructor(private readonly service: TransformService) {}

  @Post('pptx')
  async pptx(@Body() body: ExportBody, @Res() res: Response) {
    const title = body.title || 'TransformAI Presentation';
    const slides = body.slides?.length ? body.slides : [{ title, bullets: ['AI-powered content transformation', 'Generate → Verify → Refine → Deliver'] }];
    const buffer = await this.service.createPptx(title, slides, body.sources || [], body.verification || {});
    res.set({ 'Content-Type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'Content-Disposition': 'attachment; filename="transformai-presentation.pptx"' });
    res.end(buffer);
  }

  @Post('pdf')
  async pdf(@Body() body: ExportBody, @Res() res: Response) {
    const title = body.title || 'TransformAI Report';
    const sections = body.sections?.length ? body.sections : [{ heading: 'Summary', text: 'Generated by the AI Content Transformation Platform.' }];
    const buffer = await this.service.createPdf(title, sections, body.sources || [], body.verification || {});
    res.set({ 'Content-Type': 'application/pdf', 'Content-Disposition': 'attachment; filename="transformai-report.pdf"' });
    res.end(buffer);
  }

  @Post('docx')
  async docx(@Body() body: ExportBody, @Res() res: Response) {
    const title = body.title || 'TransformAI Report';
    const sections = body.sections?.length ? body.sections : [{ heading: 'Summary', text: 'Generated by the AI Content Transformation Platform.' }];
    const buffer = await this.service.createDocx(title, sections, body.sources || [], body.verification || {});
    res.set({ 'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'Content-Disposition': 'attachment; filename="transformai-report.docx"' });
    res.end(buffer);
  }
}
