import { Controller, Get, Query, Res } from "@nestjs/common";
import { Response } from "express";
import { TransformService } from "./transform.service";

@Controller("api/export")
export class ExportController {
  constructor(private readonly service: TransformService) {}
  @Get("pdf") async pdf(@Query("title") title: string, @Res() res: Response) { const b = await this.service.createPdf(title || "TransformAI Report", [{ heading: "Prototype", text: "Generated by the AI Content Transformation Platform." }]); res.set({"Content-Type":"application/pdf","Content-Disposition":"attachment; filename=transformai-report.pdf"}); res.end(b); }
  @Get("docx") async docx(@Query("title") title: string, @Res() res: Response) { const b = await this.service.createDocx(title || "TransformAI Report", [{ heading: "Prototype", text: "Generated by the AI Content Transformation Platform." }]); res.set({"Content-Type":"application/vnd.openxmlformats-officedocument.wordprocessingml.document","Content-Disposition":"attachment; filename=transformai-report.docx"}); res.end(b); }
  @Get("pptx") async pptx(@Query("title") title: string, @Res() res: Response) { const b = await this.service.createPptx(title || "TransformAI", [{ title: title || "TransformAI", bullets: ["AI-powered content transformation", "Generate → Verify → Refine → Deliver"], speakerNotes: "Prototype slide." }]); res.set({"Content-Type":"application/vnd.openxmlformats-officedocument.presentationml.presentation","Content-Disposition":"attachment; filename=transformai-presentation.pptx"}); res.end(b); }
}
