"use client";

import { useEffect, useState } from 'react';
import WorkflowCanvas from '../../components/WorkflowCanvas';

type Config = Record<string, { enabled?: boolean; research?: boolean; model?: string; tone?: string; audience?: string; detail?: string }>;
const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
const ALL_OUTPUTS = ['LinkedIn Post','X / Thread','Advisory','Executive Summary','Presentation','Infographic','Video Package'];
const KEY = 'transformai-workflow';

export default function WorkflowsPage() {
  const [source, setSource] = useState(''); const [running, setRunning] = useState(false); const [events, setEvents] = useState<any[]>([]); const [result, setResult] = useState<any>(null);
  const [research, setResearch] = useState(true); const [outputs, setOutputs] = useState(['LinkedIn Post','Executive Summary','Presentation']); const [config, setConfig] = useState<Config>({}); const [saved, setSaved] = useState(false);
  useEffect(() => { try { const s = JSON.parse(localStorage.getItem(KEY) || 'null'); if (s) { setSource(s.source || ''); setOutputs(s.outputs || ALL_OUTPUTS.slice(0,3)); setResearch(s.research !== false); setConfig(s.config || {}); } } catch {} }, []);
  const toggleOutput = (x: string) => setOutputs(s => s.includes(x) ? s.filter(y => y !== x) : [...s, x]);
  function saveWorkflow() { localStorage.setItem(KEY, JSON.stringify({ source, outputs, research, config, savedAt: new Date().toISOString() })); setSaved(true); setTimeout(() => setSaved(false), 1500); }
  function loadWorkflow() { try { const s=JSON.parse(localStorage.getItem(KEY)||'null'); if(!s) return; setSource(s.source||''); setOutputs(s.outputs||[]); setResearch(s.research!==false); setConfig(s.config||{}); setSaved(true); setTimeout(()=>setSaved(false),1500); } catch {} }
  async function runWorkflow() {
    if (!source.trim() || !outputs.length) return; setRunning(true); setResult(null); setEvents([]);
    try { const response = await fetch(`${API}/api/workflow/run`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ source, outputs, research: config.research?.research ?? research, audience: config.outputs?.audience, tone: config.outputs?.tone, detail: config.outputs?.detail, model: config.orchestrate?.model, verify: config.verify?.enabled !== false, nodes: config }) }); const data=await response.json(); setEvents(data.events||[]); setResult(data); }
    catch(error){ setEvents([{node:'Workflow',status:'Backend unavailable',detail:error instanceof Error?error.message:String(error)}]); } finally { setRunning(false); }
  }
  return <main style={{minHeight:'100vh',padding:28,background:'#09090b',color:'#fff'}}><div style={{maxWidth:1500,margin:'0 auto'}}>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'end',marginBottom:18}}><div><div style={{color:'#71717a',fontSize:12,textTransform:'uppercase',letterSpacing:'.12em'}}>TransformAI</div><h1 style={{margin:'6px 0',fontSize:28}}>Workflow Builder</h1><p style={{margin:0,color:'#a1a1aa',fontSize:13}}>Build, save and execute the agentic transformation pipeline.</p></div><div style={{display:'flex',gap:8}}><button onClick={saveWorkflow} style={{padding:'8px 12px',borderRadius:9,border:'1px solid #27272a',background:'#111113',color:'#fff'}}>{saved?'✓ Saved':'Save workflow'}</button><button onClick={loadWorkflow} style={{padding:'8px 12px',borderRadius:9,border:'1px solid #27272a',background:'#111113',color:'#a1a1aa'}}>Load</button><button onClick={()=>location.href='/'} style={{padding:'8px 12px',borderRadius:9,border:'1px solid #27272a',background:'#111113',color:'#a1a1aa'}}>← Workspace</button></div></div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 340px',gap:16,marginBottom:16}}><textarea value={source} onChange={e=>setSource(e.target.value)} placeholder="Enter source content for this workflow…" style={{minHeight:90,width:'100%',padding:14,borderRadius:12,border:'1px solid #27272a',background:'#111113',color:'#fff',resize:'vertical'}}/><div style={{display:'grid',gap:8}}><button onClick={runWorkflow} disabled={running||!source.trim()||!outputs.length} style={{border:0,borderRadius:12,background:running?'#3f3f46':'#fff',color:'#09090b',fontWeight:700,fontSize:15,cursor:running?'wait':'pointer'}}>{running?'Running workflow…':'▶ Run Workflow'}</button><label style={{padding:10,border:'1px solid #27272a',borderRadius:10,fontSize:12,color:'#a1a1aa'}}><input type="checkbox" checked={research} onChange={e=>setResearch(e.target.checked)}/> Research with Tavily</label></div></div>
    <div style={{marginBottom:12,display:'flex',gap:8,flexWrap:'wrap'}}>{ALL_OUTPUTS.map(o=><button key={o} onClick={()=>toggleOutput(o)} style={{padding:'7px 11px',borderRadius:999,border:'1px solid #27272a',background:outputs.includes(o)?'#fff':'#111113',color:outputs.includes(o)?'#09090b':'#a1a1aa',fontSize:12}}>{o}</button>)}</div>
    <WorkflowCanvas onConfigChange={setConfig}/>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:16}}><section style={{padding:18,border:'1px solid #27272a',borderRadius:14,background:'#111113'}}><h2 style={{fontSize:15,marginTop:0}}>Execution trace</h2>{events.length?events.map((e,i)=><div key={i} style={{padding:'9px 0',borderBottom:'1px solid #27272a',fontSize:13}}><div style={{display:'flex',justifyContent:'space-between'}}><span>{e.node}</span><span style={{color:e.status==='passed'||e.status==='completed'?'#86efac':e.status==='review'?'#fbbf24':'#a1a1aa'}}>{e.status}</span></div>{e.detail&&<div style={{color:'#71717a',fontSize:11,marginTop:3}}>{e.detail}</div>}</div>):<span style={{color:'#71717a',fontSize:13}}>Run the workflow to see node-by-node progress.</span>}</section><section style={{padding:18,border:'1px solid #27272a',borderRadius:14,background:'#111113'}}><h2 style={{fontSize:15,marginTop:0}}>Workflow result</h2>{result?.content?.quality&&<div style={{marginBottom:10,padding:10,borderRadius:10,border:'1px solid #27272a',color:result.content.quality.passed?'#86efac':'#fbbf24'}}>{result.content.quality.passed?'✓ Verified':'⚠ Review required'} · {result.content.quality.score}/100</div>}{result?.content?.research_sources?.length ? <div style={{marginBottom:12}}><div style={{fontSize:12,color:'#a1a1aa',marginBottom:7}}>Research sources</div>{result.content.research_sources.map((s:any,i:number)=><a key={i} href={s.url} target="_blank" rel="noreferrer" style={{display:'block',padding:'8px 0',borderBottom:'1px solid #27272a',color:'#d4d4d8',fontSize:12,textDecoration:'none'}}><strong>{s.title}</strong><div style={{color:'#71717a',marginTop:2}}>{s.snippet?.slice(0,180)}</div></a>)}</div>:null}<pre style={{maxHeight:300,overflow:'auto',whiteSpace:'pre-wrap',color:'#a1a1aa',fontSize:12}}>{result?JSON.stringify(result.content||result,null,2):'Generated content will appear here.'}</pre></section></div>
  </div></main>;
}
