"use client";

import { useEffect, useState } from 'react';
import WorkflowCanvas, { type WorkflowSnapshot } from '../../components/WorkflowCanvas';

type Config = Record<string, { enabled?: boolean; research?: boolean; model?: string; tone?: string; audience?: string; detail?: string }>;
const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
const ALL_OUTPUTS = ['LinkedIn Post','X / Thread','Advisory','Executive Summary','Presentation','Infographic','Video Package'];
const KEY = 'transformai-workflows';
function saveBlob(filename:string, blob:Blob){const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(u),500);}
function saveBase64(filename:string,data:string,mime:string){saveBlob(filename,new Blob([Uint8Array.from(atob(data),c=>c.charCodeAt(0))],{type:mime}));}

export default function WorkflowsPage(){
 const[source,setSource]=useState('');const[running,setRunning]=useState(false);const[refining,setRefining]=useState(false);const[events,setEvents]=useState<any[]>([]);const[result,setResult]=useState<any>(null);const[research,setResearch]=useState(true);const[outputs,setOutputs]=useState(['LinkedIn Post','Executive Summary','Presentation']);const[config,setConfig]=useState<Config>({});const[snapshot,setSnapshot]=useState<WorkflowSnapshot|null>(null);const[name,setName]=useState('My transformation workflow');const[savedNames,setSavedNames]=useState<string[]>([]);const[mediaBusy,setMediaBusy]=useState(false);const[mediaResult,setMediaResult]=useState<any>(null);const[videoRender,setVideoRender]=useState<any>(null);
 useEffect(()=>{try{const all=JSON.parse(localStorage.getItem(KEY)||'{}');setSavedNames(Object.keys(all));const first=all['My transformation workflow'];if(first){setSource(first.source||'');setOutputs(first.outputs||[]);setResearch(first.research!==false);setConfig(first.config||{});setSnapshot(first.snapshot||null)}}catch{}} ,[]);
 const toggleOutput=(x:string)=>setOutputs(s=>s.includes(x)?s.filter(y=>y!==x):[...s,x]);
 function saveWorkflow(){try{const all=JSON.parse(localStorage.getItem(KEY)||'{}');const item={source,outputs,research,config,snapshot,savedAt:new Date().toISOString()};all[name.trim()||'Untitled workflow']=item;localStorage.setItem(KEY,JSON.stringify(all));setSavedNames(Object.keys(all))}catch{}}
 function loadWorkflow(n:string){try{const all=JSON.parse(localStorage.getItem(KEY)||'{}');const s=all[n];if(!s)return;setName(n);setSource(s.source||'');setOutputs(s.outputs||[]);setResearch(s.research!==false);setConfig(s.config||{});setSnapshot(s.snapshot||null)}catch{}}
 function deleteWorkflow(n:string){try{const all=JSON.parse(localStorage.getItem(KEY)||'{}');delete all[n];localStorage.setItem(KEY,JSON.stringify(all));setSavedNames(Object.keys(all))}catch{}}
 async function runWorkflow(){if(!source.trim()||!outputs.length)return;setRunning(true);setResult(null);setEvents([]);setVideoRender(null);try{const response=await fetch(`${API}/api/workflow/run`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source,outputs,research:config.research?.research??research,audience:config.outputs?.audience,tone:config.outputs?.tone,detail:config.outputs?.detail,model:config.orchestrate?.model,verify:config.verify?.enabled!==false,nodes:config})});const data=await response.json();setEvents(data.events||[]);setResult(data)}catch(error){setEvents([{node:'Workflow',status:'Backend unavailable',detail:error instanceof Error?error.message:String(error)}])}finally{setRunning(false)}}
 async function refineWorkflow(){if(!result?.content)return;setRefining(true);setEvents(e=>[...e,{node:'Refine',status:'running',detail:'Fixing quality issues and re-running Quality Guardian…'}]);try{const response=await fetch(`${API}/api/transform/refine`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source,outputs,content:result.content,issues:result.content.quality?.issues||[],audience:config.outputs?.audience,tone:config.outputs?.tone,detail:config.outputs?.detail,model:config.orchestrate?.model})});const data=await response.json();if(!response.ok||data.ok===false)throw Error(data.message||'Refinement failed');setResult(data);setEvents(e=>[...e,{node:'Refine',status:data.status==='verified'?'completed':'review',detail:data.status==='verified'?'Refined output passed final verification.':'Refinement completed but still needs review.'}]);}catch(error){setEvents(e=>[...e,{node:'Refine',status:'failed',detail:error instanceof Error?error.message:String(error)}])}finally{setRefining(false)}}
 async function generateMedia(kind:'image'|'video'){if(!source.trim())return;setMediaBusy(true);setMediaResult(null);setVideoRender(null);try{const endpoint=kind==='image'?'/api/media/image':'/api/media/video-package';const prompt=kind==='image'?`Create a polished infographic visual from this source. Use concise labels, strong visual hierarchy, no unsupported facts. SOURCE: ${source.slice(0,12000)}`:`Create a factual short-form video production package from this source: ${source.slice(0,12000)}`;const r=await fetch(`${API}${endpoint}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt})});const d=await r.json();if(!r.ok||d.ok===false)throw Error(d.message||'Media generation failed');setMediaResult(d)}catch(e){setMediaResult({ok:false,message:e instanceof Error?e.message:String(e)})}finally{setMediaBusy(false)}}
 async function renderVideo(){const pkg=mediaResult?.package;if(!pkg)return;setMediaBusy(true);setVideoRender(null);try{setMediaResult((x:any)=>({...x,rendering:true}));const r=await fetch(`${API}/api/media/video-render`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({videoPackage:pkg})});const d=await r.json();if(!r.ok||d.ok===false)throw Error(d.message||'Video rendering failed');setVideoRender(d)}catch(e){setVideoRender({ok:false,message:e instanceof Error?e.message:'Video rendering failed'})}finally{setMediaBusy(false);setMediaResult((x:any)=>({...x,rendering:false}))}}
 function downloadText(filename:string,text:string,mime='text/plain'){saveBlob(filename,new Blob([text],{type:mime}))}
 return <main style={{minHeight:'100vh',padding:28,background:'#09090b',color:'#fff'}}><div style={{maxWidth:1500,margin:'0 auto'}}>
 <div style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:16,marginBottom:18}}><div><div style={{color:'#71717a',fontSize:12,textTransform:'uppercase',letterSpacing:'.12em'}}>TransformAI</div><h1 style={{margin:'6px 0',fontSize:28}}>Workflow Builder</h1><p style={{margin:0,color:'#a1a1aa',fontSize:13}}>Build, save and execute the agentic transformation pipeline.</p></div><div style={{display:'flex',gap:8,alignItems:'center'}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Workflow name" style={{width:210,padding:'8px 10px',borderRadius:9,border:'1px solid #27272a',background:'#111113',color:'#fff'}}/><button onClick={saveWorkflow} style={{padding:'8px 12px',borderRadius:9,border:'1px solid #27272a',background:'#111113',color:'#fff'}}>Save</button><select value="" onChange={e=>e.target.value&&loadWorkflow(e.target.value)} style={{padding:'8px 10px',borderRadius:9,border:'1px solid #27272a',background:'#111113',color:'#a1a1aa'}}><option value="">Load saved…</option>{savedNames.map(n=><option key={n} value={n}>{n}</option>)}</select><button onClick={()=>location.href='/'} style={{padding:'8px 12px',borderRadius:9,border:'1px solid #27272a',background:'#111113',color:'#a1a1aa'}}>← Workspace</button></div></div>
 <div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:12}}>{savedNames.map(n=><span key={n} style={{display:'inline-flex',alignItems:'center',gap:5,padding:'5px 8px',border:'1px solid #27272a',borderRadius:999,fontSize:11,color:'#a1a1aa'}}>{n}<button onClick={()=>deleteWorkflow(n)} style={{border:0,background:'transparent',color:'#71717a',cursor:'pointer'}}>×</button></span>)}</div>
 <div style={{display:'grid',gridTemplateColumns:'1fr 340px',gap:16,marginBottom:16}}><textarea value={source} onChange={e=>setSource(e.target.value)} placeholder="Enter source content for this workflow…" style={{minHeight:90,width:'100%',padding:14,borderRadius:12,border:'1px solid #27272a',background:'#111113',color:'#fff',resize:'vertical'}}/><div style={{display:'grid',gap:8}}><button onClick={runWorkflow} disabled={running||!source.trim()||!outputs.length} style={{border:0,borderRadius:12,background:running?'#3f3f46':'#fff',color:'#09090b',fontWeight:700,fontSize:15,cursor:running?'wait':'pointer'}}>{running?'Running workflow…':'▶ Run Workflow'}</button><label style={{padding:10,border:'1px solid #27272a',borderRadius:10,fontSize:12,color:'#a1a1aa'}}><input type="checkbox" checked={research} onChange={e=>setResearch(e.target.checked)}/> Research with Tavily</label></div></div>
 <div style={{marginBottom:12,display:'flex',gap:8,flexWrap:'wrap'}}>{ALL_OUTPUTS.map(o=><button key={o} onClick={()=>toggleOutput(o)} style={{padding:'7px 11px',borderRadius:999,border:'1px solid #27272a',background:outputs.includes(o)?'#fff':'#111113',color:outputs.includes(o)?'#09090b':'#a1a1aa',fontSize:12}}>{o}</button>)}</div>
 <WorkflowCanvas snapshot={snapshot} onSnapshotChange={setSnapshot} onConfigChange={setConfig}/>
 <div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}><button disabled={mediaBusy||!source.trim()} onClick={()=>generateMedia('image')} style={{padding:'8px 12px',borderRadius:9,border:'1px solid #27272a',background:'#111113',color:'#fff'}}>{mediaBusy?'Working…':'✦ Generate infographic image'}</button><button disabled={mediaBusy||!source.trim()} onClick={()=>generateMedia('video')} style={{padding:'8px 12px',borderRadius:9,border:'1px solid #27272a',background:'#111113',color:'#fff'}}>▣ Generate video package</button></div>
 {mediaResult&&<section style={{marginTop:12,padding:18,border:'1px solid #27272a',borderRadius:14,background:'#111113'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2 style={{fontSize:15,margin:0}}>Media generation</h2>{mediaResult.ok&&<span style={{fontSize:11,color:'#86efac'}}>{mediaResult.rendering?'rendering…':'ready'}</span>}</div>{mediaResult.type==='image'&&mediaResult.data?<><img src={`data:${mediaResult.mimeType||'image/png'};base64,${mediaResult.data}`} alt="Generated infographic" style={{display:'block',maxWidth:'100%',maxHeight:520,marginTop:12,borderRadius:10}}/><button onClick={()=>saveBase64(`transformai-infographic.${(mediaResult.mimeType||'image/png').includes('jpeg')?'jpg':'png'}`,mediaResult.data,mediaResult.mimeType||'image/png')} style={{marginTop:10,padding:'7px 10px',borderRadius:8,border:'1px solid #27272a',background:'#18181b',color:'#fff'}}>Download infographic</button></>:mediaResult.type==='video_package'?<><div style={{marginTop:12,padding:12,border:'1px solid #27272a',borderRadius:10,color:'#a1a1aa',fontSize:12}}><strong style={{color:'#fff'}}>{mediaResult.package?.title||'Video package'}</strong><div>{mediaResult.package?.duration_seconds||60}s · {mediaResult.package?.storyboard?.length||0} scenes · {mediaResult.package?.subtitles?.length||0} subtitle cues</div></div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}><button onClick={renderVideo} disabled={mediaBusy} style={{padding:'8px 11px',borderRadius:8,border:0,background:'#fff',color:'#09090b',fontWeight:700}}>{mediaResult.rendering?'Rendering MP4…':'▶ Render MP4'}</button><button onClick={()=>downloadText('transformai-video-package.json',JSON.stringify(mediaResult.package,null,2),'application/json')} style={{padding:'7px 10px',borderRadius:8,border:'1px solid #27272a',background:'#18181b',color:'#fff'}}>Package JSON</button><button onClick={()=>downloadText('transformai-subtitles.srt',mediaResult.package?.srt||'')} style={{padding:'7px 10px',borderRadius:8,border:'1px solid #27272a',background:'#18181b',color:'#fff'}}>SRT subtitles</button></div>{videoRender?.ok&&videoRender.data&&<div style={{marginTop:14}}><video controls playsInline src={`data:${videoRender.mimeType||'video/mp4'};base64,${videoRender.data}`} style={{width:'100%',maxHeight:560,borderRadius:10,background:'#000'}}/><button onClick={()=>saveBase64('transformai-video.mp4',videoRender.data,videoRender.mimeType||'video/mp4')} style={{marginTop:10,padding:'8px 11px',borderRadius:8,border:0,background:'#fff',color:'#09090b',fontWeight:700}}>Download MP4</button></div>}{videoRender&&!videoRender.ok&&<p style={{color:'#fbbf24',fontSize:12,marginTop:10}}>{videoRender.message}</p>}</>:<p style={{color:'#fbbf24',fontSize:12}}>{mediaResult.message}</p>}</section>}
 <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:16}}><section style={{padding:18,border:'1px solid #27272a',borderRadius:14,background:'#111113'}}><h2 style={{fontSize:15,marginTop:0}}>Execution trace</h2>{events.length?events.map((e,i)=><div key={i} style={{padding:'9px 0',borderBottom:'1px solid #27272a',fontSize:13}}><div style={{display:'flex',justifyContent:'space-between'}}><span>{e.node}</span><span style={{color:e.status==='passed'||e.status==='completed'?'#86efac':e.status==='review'?'#fbbf24':'#a1a1aa'}}>{e.status}</span></div>{e.detail&&<div style={{color:'#71717a',fontSize:11,marginTop:3}}>{e.detail}</div>}</div>):<span style={{color:'#71717a',fontSize:13}}>Run the workflow to see node-by-node progress.</span>}</section><section style={{padding:18,border:'1px solid #27272a',borderRadius:14,background:'#111113'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10}}><h2 style={{fontSize:15,margin:0}}>Workflow result</h2>{result?.content?.quality&&!result.content.quality.passed&&<button onClick={refineWorkflow} disabled={refining} style={{padding:'8px 11px',borderRadius:8,border:0,background:'#fff',color:'#09090b',fontWeight:700}}>{refining?'Refining…':'↻ Refine & Re-verify'}</button>}</div>{result?.content?.conflict_count>0&&<div style={{marginTop:10,padding:10,border:'1px solid #713f12',borderRadius:10,color:'#fbbf24',fontSize:12}}>⚠ {result.content.conflict_count} source conflict(s) · {result.content.unresolved_conflicts||0} unresolved. Review disputed claims before treating them as settled facts.</div>}{result?.content?.quality&&<div style={{marginTop:10,marginBottom:10,padding:10,borderRadius:10,border:'1px solid #27272a',color:result.content.quality.passed?'#86efac':'#fbbf24'}}>{result.content.quality.passed?'✓ Verified':'⚠ Review required'} · {result.content.quality.score}/100{result.content.quality.issues?.length?<div style={{marginTop:5,color:'#a1a1aa'}}>{result.content.quality.issues.join(' · ')}</div>:null}</div>}{result?.content?.research_sources?.length?<div style={{marginBottom:12}}><div style={{fontSize:12,color:'#a1a1aa',marginBottom:7}}>Research sources</div>{result.content.research_sources.map((s:any,i:number)=><a key={i} href={s.url} target="_blank" rel="noreferrer" style={{display:'block',padding:'8px 0',borderBottom:'1px solid #27272a',color:'#d4d4d8',fontSize:12,textDecoration:'none'}}><strong>{s.title}</strong><div style={{color:'#71717a',marginTop:2}}>{s.snippet?.slice(0,180)}</div></a>)}</div>:null}<pre style={{maxHeight:300,overflow:'auto',whiteSpace:'pre-wrap',color:'#a1a1aa',fontSize:12}}>{result?JSON.stringify(result.content||result,null,2):'Generated content will appear here.'}</pre></section></div>
 </div></main>;
}
