"use client";

import { useState } from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:3001";
type Source={id:string;name:string;type:"text"|"url";value:string};
type Conflict={id?:string;topic?:string;severity?:string;resolution?:string;recommendation?:string;claim_a?:{text?:string;source_id?:string;source_name?:string;excerpt?:string};claim_b?:{text?:string;source_id?:string;source_name?:string;excerpt?:string}};
export default function SourcesPage(){const[sources,setSources]=useState<Source[]>([{id:crypto.randomUUID(),name:"Source 1",type:"text",value:""}]);const[result,setResult]=useState<any>(null);const[analysis,setAnalysis]=useState<any>(null);const[busy,setBusy]=useState(false);const update=(id:string,p:Partial<Source>)=>setSources(x=>x.map(s=>s.id===id?{...s,...p}:s));const add=()=>setSources(x=>[...x,{id:crypto.randomUUID(),name:`Source ${x.length+1}`,type:"text",value:""}]);
async function analyze(){const usable=sources.filter(s=>s.value.trim());if(!usable.length)return;setBusy(true);try{const r=await fetch(`${API}/api/transform`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sources:usable.map(s=>s.type==="url"?{id:s.id,name:s.name,type:"url",url:s.value}:{id:s.id,name:s.name,type:"text",text:s.value}),outputs:["Executive Summary"],research:false,verify:true})});const d=await r.json();if(!r.ok||d.ok===false)throw Error(d.message||"Analysis failed");setAnalysis(d.content);setResult(d)}catch(e){setResult({ok:false,message:e instanceof Error?e.message:String(e)})}finally{setBusy(false)}}
return <main className="workspace-shell"><section className="workspace-card"><div className="section-heading"><div><span className="eyebrow">CONTENT INTELLIGENCE</span><h1>Multi-source workspace</h1><p>Combine sources, detect contradictions, and preserve provenance before generation.</p></div><button className="secondary-button" onClick={add}>+ Add source</button></div><div className="source-stack">{sources.map(s=><article className="source-card" key={s.id}><div className="source-card-header"><input value={s.name} onChange={e=>update(s.id,{name:e.target.value})}/><select value={s.type} onChange={e=>update(s.id,{type:e.target.value as Source["type"],value:""})}><option value="text">Text</option><option value="url">URL</option></select>{sources.length>1&&<button className="ghost-button" onClick={()=>setSources(x=>x.filter(y=>y.id!==s.id))}>Remove</button>}</div><textarea rows={7} placeholder={s.type==="url"?"https://example.com/article":"Paste source material here..."} value={s.value} onChange={e=>update(s.id,{value:e.target.value})}/></article>)}</div><button className="primary-button" disabled={busy} onClick={analyze}>{busy?"Detecting conflicts...":"Analyze & detect conflicts"}</button>{result&&!result.ok&&<div className="source-result"><div className="result-title">Analysis failed</div><p>{result.message}</p></div>}{analysis&&<div className="source-result"><div className="result-title">{analysis.conflict_count?`⚠ ${analysis.conflict_count} source conflict(s) detected`:"✓ No source conflicts detected"}</div>{analysis.unresolved_conflicts>0&&<p><strong>Review required:</strong> {analysis.unresolved_conflicts} unresolved conflict(s) remain. The generator is instructed not to silently choose a source.</p>}{(analysis.conflicts||[]).map((c:Conflict,i:number)=><article key={c.id||i} className="source-card" style={{marginTop:12}}><div className="source-card-header"><strong>{c.topic||"Source conflict"}</strong><span className="chip selected">{(c.severity||"review").toUpperCase()}</span></div><p><strong>Source A · {c.claim_a?.source_name||c.claim_a?.source_id||"Unknown"}</strong><br/>{c.claim_a?.text}</p><small>{c.claim_a?.excerpt}</small><hr/><p><strong>Source B · {c.claim_b?.source_name||c.claim_b?.source_id||"Unknown"}</strong><br/>{c.claim_b?.text}</p><small>{c.claim_b?.excerpt}</small><p><strong>Recommendation:</strong> {c.recommendation||"Needs review before asserting either claim."}</p></article>)}</div>}</section></main>}
